### ISSUE TITLE
Cannot infer entry chunk when use multiple entry

### ISSUE THREAD

**Issue by GitNiko** [callstack/repack#257]
```js
{
//...
    entry: {
      base: [
        ...Repack.getInitializationEntries(reactNativePath, {
              hmr: devServer && devServer.hmr,
        }),
      ],
      entry: './index'
}
```
throw exception: 
```sh
HookWebpackError: Cannot infer entry chunk - this should have not happened.
    at makeWebpackError (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/home/coder/project/eact-ative/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at fn (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:480:17)
    at Hook.eval [as callAsync] (eval at create (/home/coder/project/eact-ative/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/coder/project/eact-ative/example/app/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3057:34)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3105:10
    at symbolIterator (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:3485:9)
    at timesSync (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:3463:5)
    at Compilation.createChunkAssets (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:4526:12)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3100:14
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3277:6
    at /home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:2818:7
    at done (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:3522:9)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3240:8
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3349:32
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/coder/project/eact-ative/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/CacheFacade.js:137:15)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3349:11
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:91:34
    at Array.<anonymous> (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/cache/MemoryCachePlugin.js:45:13)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:91:19
    at Hook.eval [as callAsync] (eval at create (/home/coder/project/eact-ative/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/CacheFacade.js:111:15)
    at Compilation._codeGenerationModule (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3319:9)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3226:11
    at arrayIterator (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:3467:9)
    at timesSync (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:3463:5)
    at runIteration (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3206:13)
    at Compilation._runCodeGenerationJobs (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3281:3)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3037:12
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3277:6
    at /home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:2818:7
    at done (/home/coder/project/eact-ative/example/app/node_modules/neo-async/async.js:3522:9)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3240:8
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3349:32
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/coder/project/eact-ative/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/CacheFacade.js:137:15)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Compilation.js:3349:11
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:91:34
    at Array.<anonymous> (/home/coder/project/eact-ative/example/app/node_modules/webpack/lib/cache/MemoryCachePlugin.js:45:13)
    at /home/coder/project/eact-ative/example/app/node_modules/webpack/lib/Cache.js:91:19
```

**Comment by RafikiTiki** [comment]
Hi @GitNiko, thanks for reporting this!

Would you be able to create a repro repository with the config that is causing the above error? The only difference I could spot between the part of the config you've pasted above and the one from mentioned in [repack docs](https://github.com/callstack/repack/blob/main/templates/webpack.config.mjs) is that in your case the file extension is omitted.

**Comment by GitNiko** [comment]
Hi @RafikiTiki , thanks for your replay. 
The entry options is type of **array** in repack docs, and the type is **object** in my example.Does it not support type **object** ?
Additionally, my purpose is to name each chunk.
> If a string or array of strings is passed, the chunk is named main. If an object is passed, each key is the name of a chunk, and the value describes the entry point for the chunk. [webpack doc](https://webpack.js.org/configuration/entry-context/#naming)

```js
// repack docs
entry: [ // type array
      ...Repack.getInitializationEntries(reactNativePath, {
        hmr: devServer && devServer.hmr,
      }),
      entry,
    ],
// my example
entry: { // type object
      base: [
        ...Repack.getInitializationEntries(reactNativePath, {
              hmr: devServer && devServer.hmr,
        }),
      ],
      entry: './index'
```

**Comment by reline** [comment]
@GitNiko taking a look at the webpack docs, the default entry chunk name is `main`, not `base`.
https://webpack.js.org/concepts/entry-points/#single-entry-shorthand-syntax

So to avoid altering any entry or output names that Repack expects, we can name the react-native entry point to `main` and change the main output bundle name to `index.bundle` while still naming every other bundle whatever we want.
```js
entry: {
  main: [
    ...Repack.getInitializationEntries(reactNativePath, {
      hmr: devServer && devServer.hmr,
    }),
    entry,
  ],
  someOtherEntry: './other.js',
},
...
output: {
  clean: true,
  path: path.join(dirname, 'build/generated', platform),
  filename: (pathData) => {
    return pathData.chunk.name === 'main' ? 'index.bundle' : '[name].bundle';
  },
  chunkFilename: '[name].chunk.bundle',
  publicPath: Repack.getPublicPath({platform, devServer}),
},
```

**Comment by GitNiko** [comment]
@reline Thank you for your help! That's a good way.
