### ISSUE TITLE
Codepush Main bundle crash in Release mode

### ISSUE THREAD

**Issue by mobile-sion** [callstack/repack#282]
I got crashed when update App by Codepush in release mode on both android and iOS (development mode works well)
What is a problem?

![Screenshot 2022-12-28 at 11 14 15](https://user-images.githubusercontent.com/121469747/209756693-4c0e4f1f-159c-4b56-99bd-209cfdf1f21a.png)

**Comment by RafikiTiki** [comment]
Hey, thanks for creating this issue!

Have you read this page in repack docs: https://re-pack.netlify.app/docs/code-splitting/code-push? Are you using any form of code-splitting? If yes, then that's not officially supported by repack and it can and probably will result in issues.

However, we are open to discussion here and you are more than welcome to help with improving repack and code-push together as both projects aim to accomplish different use cases

**Comment by vlack-coder** [comment]
Hi @RafikiTiki  my app is crashing in release mode with codepush... I'm getting the same error as the OP and screenshot is attached below. Thank you

<img width="831" alt="okiop" src="https://github.com/callstack/repack/assets/56041655/78f8cde5-56db-41aa-8c40-a7c23bfa81bc">


digest=============com.momo.consumer.devcom.facebook.react.common.JavascriptException: ReferenceError: Property '__webpack_require__' doesn't exist, js engine: hermes, stack:
getXX:XX
anonymousXX:XX
hXX:XX
dXX:XX
iXX:XX
globalXX:

at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:XX)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:XX)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:XX)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:XX)
at android.os.Handler.dispatchMessage(Handler.java:XX)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:XX)
at android.os.Looper.loopOnce(Looper.java:XX)
at android.os.Looper.loop(Looper.java:XX)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$.run(MessageQueueThreadImpl.java:XX)
at java.lang.Thread.run(Thread.java:XX)
