### ISSUE TITLE
TypeError: Repack.getDirname is not a function

### ISSUE THREAD

**Issue by DW1219** [callstack/repack#307]
I just worked as below sequence for testing TesterApp(github sample), but error is occur on node.
How can I solve this error?

git clone TesterApp sample
cd repack/packages/TesterApp
npm install
npx react-native webpack-start
react-native run-android
 
>> error

/Users/dongwooyoo/Documents/react_native_study/bundleSplitUseRepack/repack/packages/TesterApp/node_modules/metro-hermes-compiler/src/emhermesc.js:77
          throw ex;
          ^

TypeError: Repack.getDirname is not a function
    at default (file:///Users/dongwooyoo/Documents/react_native_study/bundleSplitUseRepack/repack/packages/TesterApp/webpack.config.mjs:34:26)
    at loadWebpackConfig (/Users/dongwooyoo/Documents/react_native_study/bundleSplitUseRepack/repack/packages/TesterApp/node_modules/@callstack/repack/dist/webpack/loadWebpackConfig.js:22:18)
    at async main (/Users/dongwooyoo/Documents/react_native_study/bundleSplitUseRepack/repack/packages/TesterApp/node_modules/@callstack/repack/dist/webpack/webpackWorker.js:19:25)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:545:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! testerapp@0.0.1 start: `react-native webpack-start`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the testerapp@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by chudaotrucnhan** [comment]
In my case, change node version to 18.0.0
