### ISSUE TITLE
File index.bundle for android not found in compilation assets

### ISSUE THREAD

**Issue by cypcap** [callstack/repack#316]
Hi everyone,

I have got this issues when I run a react-native app with webpack. Seems something wrong with webpack bundling? 

Thanks:

My app error log:

 [15:15:33.412Z][DevServer] File index.bundle for android not found in compilation assets {
  reqId: 'req-3',
  stack: 'Error: File index.bundle for android not found in compilation assets\n' +
    '    at /Users/MacBook/Documents/projects/test/RNDemo/RepackDemo/node_modules/@callstack/repack/dist/webpack/Compiler.js:174:20\n' +
    '    at /Users/MacBook/Documents/projects/test/RNDemo/RepackDemo/node_modules/@callstack/repack/dist/webpack/Compiler.js:83:52\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at callPendingResolvers (/Users/MacBook/Documents/projects/test/RNDemo/RepackDemo/node_modules/@callstack/repack/dist/webpack/Compiler.js:83:32)\n' +
    '    at Worker.<anonymous> (/Users/MacBook/Documents/projects/test/RNDemo/RepackDemo/node_modules/@callstack/repack/dist/webpack/Compiler.js:104:9)\n' +
    '    at Worker.emit (node:events:390:28)\n' +
    '    at MessagePort.<anonymous> (node:internal/worker:232:53)\n' +
    '    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)\n' +
    '    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)',
  type: 'Error'

**Comment by RafikiTiki** [comment]
Could you please provide more context of the environment you're trying to run repack project in (are you running the app in an emulator or physical device etc)? And possibly a reproduction repo – that'll help me to analyze the problem.

One quick idea – double-check if you've run the `adb reverse` command to make sure the Android device has access to the dev server.

**Comment by MANOJPATRA1991** [comment]
I am also getting the exact same error. I am trying to run on a physical device. I have verified with `adb reverse`. It has access to dev server.

**Comment by marciowolff** [comment]
Também estou com o mesmo erro, mas só acontece ao rodar no emulador do android studio, no xCode funciona

**Comment by RafikiTiki** [comment]
@MANOJPATRA1991 thanks for the reproduction repo! I was able to reproduce the issue, and I will investigate it.

**Comment by RafikiTiki** [comment]
So the fix for that is a little tricky to find but very easy to implement. You need to set the `output.filename` in webpack config to be in line with what React Native expects: `index.bundle`. Without manually setting that, webpack will use scriptId (which in the development mode is `main`, which will produce `main.bundle` instead of `index.bundle` expected by the React Native by default). You should be able to change the default React Native behavior by modifying a property in the app's build.gradle file, but I suggest updating the webpack config instead.

This is already there in [the webpack config template in the Repack repository](https://github.com/callstack/repack/blob/main/templates/webpack.config.mjs#L111); I highly suggest using a template from there whenever you're creating a new project – it's the source of truth that we are using at the Callstack. We try our best to keep these templates up to date.

Attaching git diff for reference:
```diff
diff --git a/webpack.config.mjs b/webpack.config.mjs
index dfcca58..d1337f5 100644
--- a/webpack.config.mjs
+++ b/webpack.config.mjs
@@ -99,7 +99,7 @@ export default (env) => {
     output: {
       clean: true,
       path: path.join(dirname, 'build/generated', platform),
-      filename: '[name].bundle',
+      filename: 'index.bundle',
       chunkFilename: '[name].chunk.bundle',
       publicPath: Repack.getPublicPath({ platform, devServer }),
     },
     ```

**Comment by ckken** [comment]
when filename: 'index.bundle' the splitChunks is no work!
