### ISSUE TITLE
undefined is not a function in XMLHttpRequest.js on bundling app with repack

### ISSUE THREAD

**Issue by MANOJPATRA1991** [callstack/repack#337]
## Bad bundle issue

I am getting the following error on running the command

`react-native webpack-bundle --platform android --entry-file index.js --dev=false`

<img width="252" alt="Screenshot 2023-04-11 at 11 09 34 AM" src="https://user-images.githubusercontent.com/16289802/231066363-d30aef07-a517-4933-8348-43f7e470e2a1.png">

Logs from Android Studio:

```
Exception in native call
                                                                                                    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-04-08 07:52:25.885 24081-24346 ReactNativeJNI          com.my11circle.android.stage         E  Attempting to call JS callback on a bad application bundle: 0
2023-04-08 07:52:25.886 24081-24346 unknown:ReactNative     com.my11circle.android.stage         E  Exception in native call
                                                                                                    java.lang.RuntimeException: Attempting to invoke JS callback on a bad application bundle.
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by RafikiTiki** [comment]
The command you use (`react-native webpack-bundle --platform android --entry-file index.js --dev=false`) is intended to build the javascript bundles, not to run the application. How are you consuming the bundle in the app?

Please share all the steps and a reproduction repo that result in the error.

**Comment by jbroma** [comment]
Closing as issue became stale and no reproduction was provided. If you are still facing this issue please open a new issue.
